title: Creative Space
subtitle: Toți avem nevoie de un hobby
author: Creative Space
email:
avatar: assets/images/avatar.jpg

baseurl: "/"
url: "https://creativespace.ro"

# Social settings
facebook_url: https://www.facebook.com/creativespacetm/
github_url: https://github.com/CreativeSpaceTM
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: https://join.slack.com/t/creativespacetm/shared_invite/enQtNzgyNzg3MzQwNjU4LTUyNWI2YTFjZGQ2ZjU3OTAyYjZhM2ZjZjk5ZmYyZTQ5ZmE0NGYwMGQ0MjM2NDM2MTkxYzE2NTY5M2UwZmEzNTQ
twitter_url: https://twitter.com/CreativeSpaceTM

# Google Analytics Tracking ID goes here:
google_analytics: UA-19732240-5

# The following settings are NECESSARY for the Prologue theme to run:
# theme: jekyll-theme-prologue
collections: [sections, camere]
